### ISSUE TITLE
upstream/mainline kernel works with a one-line patch

### ISSUE THREAD

**Issue by colemickens** [samueldr/wip-pinebook-pro#21]
```nix
  {
      kernelPackages = lib.mkForce pkgs.linuxPackages_latest;
      kernelPatches = [{
        name = "pinebook-disable-dp";

        # https://patchwork.kernel.org/project/linux-rockchip/patch/20200924063042.41545-1-jhp@endlessos.org/
        patch = ./pbp-disable-dp.patch;
      }];
  }
```

patch: https://patchwork.kernel.org/project/linux-rockchip/patch/20200924063042.41545-1-jhp@endlessos.org/

```patch
diff --git a/arch/arm64/boot/dts/rockchip/rk3399-pinebook-pro.dts b/arch/arm64/boot/dts/rockchip/rk3399-pinebook-pro.dts
index 06d48338c836..d624c595c533 100644
--- a/arch/arm64/boot/dts/rockchip/rk3399-pinebook-pro.dts
+++ b/arch/arm64/boot/dts/rockchip/rk3399-pinebook-pro.dts
@@ -380,7 +380,7 @@  mains_charger: dc-charger {
 };
 
 &cdn_dp {
-	status = "okay";
+	status = "disabled";
 };
 
 &cpu_b0 {
```

Upstream/mainline linux works if you apply that patch. Early display doesn't work. That patch avoids the DP probe failure from preventing the internal display from working.

```
❯ ssh cole@pinebook.ts.r10e.tech uname -a
Linux pinebook 5.11.2 #1-NixOS SMP Fri Feb 26 09:08:38 UTC 2021 aarch64 GNU/Linux


```

**Comment by samueldr** [comment]
Ooh... If we built *only* that dtb we could even re-use the mainline package as built by Nixpkgs, or are there missing config options?

**Comment by colemickens** [comment]
That should be it. This is the rest of the config. I don't have it plugged in, but I'm SSHed, so wifi at least works as well. https://github.com/colemickens/nixcfg/blob/84fdabb3c22b594c1bbc2ebaa2588718fb485dfe/hosts/pinebook/configuration.nix

**Comment by samueldr** [comment]
No need patch anymore:

 - https://github.com/torvalds/linux/commit/2513fa5c25d42f55ca5f0f0ab247af7c9fbfa3b1

Since v5.16 the equivalent change is in the device tree already.

Also

 - https://github.com/Tow-Boot/Tow-Boot/pull/109
