### ISSUE TITLE
investigate some patches

### ISSUE THREAD

**Issue by colemickens** [samueldr/wip-pinebook-pro#23]
mostly notes to self:

https://forum.manjaro.org/t/nvme-support-in-uboot-pinebookpro-2021-04-1/63774

https://github.com/nadiaholmquist/pbp-packages

particularly the u-boot one(s) related to rebooting

**Comment by samueldr** [comment]
NVMe in Tow-Boot reportedly just works. So I guess it's not needed anymore.

Though, if you think there is something to re-evaluate in Tow-Boot, feel free to open an equivalent issue!
