### ISSUE TITLE
Clarification request for EFI and poweroff

### ISSUE THREAD

**Issue by shadowrylander** [samueldr/wip-pinebook-pro#34]
Hello!

I have a few question:

1. Under [EFI and poweroff](https://github.com/samueldr/wip-pinebook-pro#efi-and-poweroff) in the `README` here you state:

> ... A [workaround exists](https://github.com/Tow-Boot/Tow-Boot/commit/818cae1b84a7702f2a509927f2819900c2881979#diff-20f50d9d8d5d6c059b87ad66fbc5df26d9fc46251763547ca9bdcc75564a4368), and is built in recent Tow-Boot (no prebuilt releases at this time).

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; But in the latest release for `Tow-Boot`, you state:

> The suspend patch for the Pinebook Pro has been dropped, as it was mainlined.

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Does this mean I can directly install U-Boot instead?

2. How would I go about building an installation `iso` using this? I unfortunately can't use the [isos' with `u-boot` embedded](https://github.com/Mic92/nixos-aarch64-images) due to this issue [here](https://github.com/Mic92/nixos-aarch64-images/issues/8).

Thank you kindly for the help! Sorry; I'm still a little new to `NixOS`!

**Comment by samueldr** [comment]
The suspend and poweroff issues are unrelated.

The poweroff workaround exists, and is implemented in Tow-Boot.

The suspend work is mainlined, so yes, any platform firmware build from mainline U-Boot and TF-A should work.

Although I'm biased, I would recommend using Tow-Boot anyway, since installing to SPI Flash is not trivial for other builds. Basically none of the U-Boot pre-builts I know of are produced in a way that will be flashable to SPI Flash.

* * *

I have some [almost complete notes about NixOS on ARM with UEFI](https://nixos.wiki/wiki/NixOS_on_ARM/UEFI); you don't need to build the iso. The generic UEFI iso works. **But**, there is a catch. The `new_kernel` variant is not being built due to the inclusion of `zfs` in the build, which isn't updated for 5.16 yet. So right now you'd boot with a 5.15 iso, but updating the channels in the system before installing, or referencing a newer revision would allow you to use 5.16 (if you're not using zfs, or if you do the required things for it to work).

Note that [there are links to the iso image builds here](https://nixos.wiki/wiki/NixOS_on_ARM/UEFI#Getting_the_installer_image_.28ISO.29).

**Comment by shadowrylander** [comment]
Ok, so could you give my a short overview of how I would install to a ZFS root on the internal emmc storage from a microsd card? Should I dd over the generic iso to the microsd card and use that to install a config with the pinebook config imported? Then dd over a tow-boot image to the first partition of the emmc? Do I need to change the bootloader settings of the config?

**Comment by samueldr** [comment]
A really short overview would be:

 - Ensure Tow-Boot is flashed to SPI
 - Burn the iso image to USB (SD is fine too)
 - Do as you would for an x86_64 UEFI system for a ZFS root install (I don't really know off the top of my head). This includes setting up an ESP, which may or may not be used also as the boot partition, depending on your usual setup.
 - Be mindful about the EFI setup

```nix
{
  # This is needed as EFI Variables are not writable in U-Boot yet
  boot.loader.efi.canTouchEfiVariables = false;
  # Either you can use rEFInd manually copied to the fallback boot location or
  boot.loader.grub.efiInstallAsRemovable = true;
}
```

[There are notes about rEFInd on the NixOS wiki](https://nixos.wiki/wiki/rEFInd).


You don't strictly need the pinebook pro config included, but at the very least the modules list will make your life easier in stage-1 if there are issues. Other changes are quality-of-life changes, which yeah, you probably want.

I highly recommend **not** installing Tow-Boot to the eMMC. There are no reason to do so. Recovering from a bad flash to SPI is only marginally harder than recovering from a bad flash to eMMC. The Tow-Boot releases are exhaustively tested to ensure you're not left in a bad situation.

**Comment by shadowrylander** [comment]
Ah... Sorry, but could you also point me towards some resources to flash Tow-Boot to the SPI...? Would [these](https://github.com/pcm720/u-boot-build-scripts/releases/tag/v2020.07-1) instructions work, for example? Would I just have to replace their image with yours? If so, where could I get your images? They don't seem to be in the recent tow-boot release sections.

**Comment by samueldr** [comment]
Those instructions wouldn't work as they are.

The easiest method is to

 1. Make sure there is no U-Boot on eMMC ([Neutering instructions](https://github.com/Tow-Boot/Tow-Boot/issues/47))
 2. Write the `spi.installer.img` image to SD `dd if=spi.installer.img of=/dev/XXX bs=1M oflag=direct,sync status=progress`
 3. Boot that image, you may need to use ESC to break into the boot menu, and select "Boot from SD".
 4. In the menu, select "Flash firmware to SPI"

**Comment by shadowrylander** [comment]
In the neutering instructions, do I have to do both steps, or just the first? In addition, where do I actually get `spi.installer.img`...?

**Comment by samueldr** [comment]
Since we're talking about neutering the platform firmware written to eMMC, only the instructions under *eMMC*

```
# dd if=/dev/zero of=/dev/mmcblkX bs=512 seek=64 count=16
```

Tow-Boot can be downloaded on the *Releases* page in the GitHub repo

 - https://github.com/Tow-Boot/Tow-Boot/releases

There is a collapsed section named *Assets*, open it and you should be able to find the list of release artifacts.

**Comment by shadowrylander** [comment]
I'm assuming it's in the pinebook pro tarball?

**Comment by samueldr** [comment]
Yes since you are installing on a Pinebook Pro.

**Comment by shadowrylander** [comment]
Got it; thank you kindly for your patience! I'll try it out and report back! Shall I close this issue in the meantime?

**Comment by samueldr** [comment]
I took care of it.

**Comment by shadowrylander** [comment]
Ah, quick question: how can I check if uboot has been removed from the emmc? I used `dd if=/dev/zero of=/dev/mmcblk2 bs=512 seek=64 count=16`, but `blkid` and `lsblk` still show an intact partitioning setup.

**Comment by samueldr** [comment]
That command only breaks the starting location checked by the boot ROM. It will not affect the partition scheme. Note that the partitions are not used by the boot ROM, it only checks direct offsets.

**Comment by shadowrylander** [comment]
Great! So I'm good to move onto step 2, writing the `spi` image?

**Comment by samueldr** [comment]
Possibly. I don't know what you have done, or are currently doing.

**Comment by shadowrylander** [comment]
Right; should've realized. Either way, flashing the `spi` image succeeded! However, do you know if I can use `systemd-boot` in the configuration? For some reason grub isn't working with my zfs setup.

**Comment by shadowrylander** [comment]
Also, do I use the regular installer, such as the [gnome image](https://nixos.org/download.html#nixos-iso) from nixos.org, or an SD image, from the [arm page](https://nixos.wiki/wiki/NixOS_on_ARM#SD_card_images_.28SBCs_and_similar_platforms.29)?

**Comment by samueldr** [comment]
You can use an SD image, but the **AArch64** UEFI iso should work as well:

There are notes on the wiki:

 - https://nixos.wiki/wiki/NixOS_on_ARM/UEFI

`systemd-boot` should now work, but I'm unsure if what made it work is in the stable channels.

**Comment by shadowrylander** [comment]
Alright; so I'm currently attempting to install nixos on ZFS on the internal emmc, and will report back when done!

**Comment by shadowrylander** [comment]
It works! The only issue is that, when the system boots, it gets stuck on two or three kernel messages for a minute or two, then allows me to log in.
