### ISSUE TITLE
OF: graph: no port mode found

### ISSUE THREAD

**Issue by criena** [samueldr/wip-pinebook-pro#37]
I feel a bit guilty about opening this issue, since I believe it's a layer 8 problem and not a bug. Google had nothing on the matter though and in the nixos-aarch64 chat I didn't get any reaction either.

I cloned the repository and added the pinebook_pro.nix into the configuration.nix (right under the import of hardware-configuration.nix). The root partition (btrfs) is encrypted (LUKS) and /boot is unencrypted ext4. The installation went perfectly fine, no errors. But when I try to boot from the eMMC, I get the following error message (and the boot process is halted):

> OF: graph: no port node found in /i2c@ff3d0000/fusb30x@22

![IMG_5455a](https://user-images.githubusercontent.com/19910559/161721691-6d941cf3-8ed7-4024-b64b-6ec41d397793.jpg)

I don't think the problem has to do with my LUKS setup, since it happens very early in the process. But on the other side, the installer SD card (unencrypted obviously) works as expected.

**Comment by WesleyAC** [comment]
@criena did you ever figure this out? Running into the same issue with nixos-hardware (on almost the exact same setup, LUKS and btrfs, although it happens before I type in any password) and trying to figure it out.

**Comment by samueldr** [comment]
→ Continuing in the `nixos-hardware` issue
