### ISSUE TITLE
NanoPC T4

### ISSUE THREAD

**Issue by insipx** [samueldr/wip-pinebook-pro#5]
Wondering if this would work with NanoPC T4. It's got the same RK3399 chip and SD/EMCC storage

**Comment by samueldr** [comment]
A setup inspired by this, just like [my other repo](https://github.com/samueldr/wip-roc-rk3399-pc) may as well work. As long as you get a kernel that works with it (mainline maybe does), and a mainline u-boot, this can be tweaked accordingly.

**Comment by insipx** [comment]
cool!
