### ISSUE TITLE
encrypted nvme

### ISSUE THREAD

**Issue by paumr** [samueldr/wip-pinebook-pro#6]
Hi,

did anyone manage to boot from an encrypted nvme drive?
If so could you share your setup?

**Comment by paumr** [comment]
Closing this issue, as in retrospective it's not relevant.
The initial question should have been "how can i boot nixos from the nvme adapter?", which didn't work since it wasn't detected in the early boot stages.
It seems to be solved with a kernel patch, however i didn't have time to verify that yet.

**Comment by glglwty** [comment]
Do you have a pointer on how you made this work? Partition the nvme in GPT, create /boot partition and encrypt / just like on x86 and the u-boot on emmc would be able boot it?

**Comment by samueldr** [comment]
The broad strokes is you'll need a u-boot for the pinebook pro with NVME support (mine doesn't yet) and a kernel that also supports NVME. Then yeah, partition the NVME drive, any scheme should work, though note that u-boot will look at partitions marked bootable with the default distro boot scheme, which I'm not sure how to do with a GPT partition scheme. Unless you boot using the minimal UEFI support in u-boot, which may or may not work.
