### ISSUE TITLE
Use Mobile NixOS' boot selection GUI

### ISSUE THREAD

**Issue by samueldr** [samueldr/wip-pinebook-pro#8]
See NixOS/mobile-nixos#80.

The big idea is to setup the boot so that:

 * u-boot boots a mobile-nixos stage-1

The main drawback would be the loss of trivial kernel updates until NixOS/mobile-nixos#82 is implemented.

NixOS/mobile-nixos#83 blocks this.

**Comment by samueldr** [comment]
See https://github.com/NixOS/mobile-nixos/pull/94.

This is usable right now, but needs some finessing to integrate in an existing system. It's something I intend to work on at some point for my own use.

**Comment by tgunnoe** [comment]
is this the same as `feature/u-boot-gfx`? 

Can this be adapted to other NixOS compatible platforms? the one i'm looking at adapting is armv7 [running on Novena](https://nixos.wiki/wiki/NixOS_on_ARM/Novena)

**Comment by samueldr** [comment]
Different solution to the same problem.

This is not something I'm working on anymore as a target since now we have the, admittedly better, u-boot graphical init.

Anyway, oops, this is now possible:

 * https://github.com/NixOS/mobile-nixos/pull/162
 * https://github.com/samueldr/mobile-nixos-extra-devices/tree/master/devices/pine64-pinebookpro

But this still has the Mobile NixOS caveat of making kernel upgrades awkward.

You might be interested in trying to get the Mobile NixOS stage-1 for the Novena working, but the better solution would be to get a u-boot that uses the display output.
